### PR TITLE
feat: add logic to sort swapchain formats

### PR DESCRIPTION
**Pull request by pollend**
this logic attempts to sort swapchains and pick the best swapchain given criteria for SwapChainFormat. I place the colorspace at the highest bit so its sorted by colorspace then by formats. formats have to be unorm where the bitwidth matches the criteria. code feels a bit overbuilt though. 

does it matter if its bgra vs rgba depending on the driver? should it be more consistent in the selection I don't think it should matter?

https://github.com/NVIDIAGameWorks/NRI/issues/102

### CODE REVIEW

**Comment by dzhdanNV** [comment]
Thanks for improving this. I have a few questions:

1. Sometimes you use:
```c++
((!formatProps.isSrgb) << 4) | ((surface.colorSpace == X) << 4);
```
Sometimes:
```c++
((!formatProps.isSrgb) << 4) | ((surface.colorSpace == X) << 5);
```
Why?

2. `case nri::SwapChainFormat::BT709_G10_16BIT:` uses `priority_BT709_G22_16BIT`. Why?

3. Should `formatProps.isSrgb` be used for `10 bits`? 10 bit RGB doesn't have `sRGB` evil-twin format (but swap chain has supports gamma 2.2 transfer function).

P.S. Probably I understand why, but would like to hear your explanation.

**Comment by pollend** [comment]
> Thanks for improving this. I have a few questions:
> 
>     1. Sometimes you use:
> 
> 
> ```c++
> ((!formatProps.isSrgb) << 4) | ((surface.colorSpace == X) << 4);
> ```
> 
> Sometimes:
> 
> ```c++
> ((!formatProps.isSrgb) << 4) | ((surface.colorSpace == X) << 5);
> ```
> 
> Why?
> 
>     2. `case nri::SwapChainFormat::BT709_G10_16BIT:` uses `priority_BT709_G22_16BIT`. Why?
> 
>     3. Should `formatProps.isSrgb` be used for `10 bits`? 10 bit RGB doesn't have `sRGB` evil-twin format (but swap chain has supports gamma 2.2 transfer function).
> 
> 
> P.S. Probably I understand why, but would like to hear your explanation.

probably oversight on my end. I would drop the srgb check from 10bits and for the other formats how would you prioritize those? im not familiar with what formats are available or what to expect?

**Comment by dzhdanNV** [comment]
Sure. This logic seems GAPI irrelevant, so better share it between D3D11/D3D12/VK.

Could you please formulate your problem? I understand that my simple checks "are not enough", but I didn't get which set of surface formats you have and which surface format from this list is not selected being desired?

**Comment by dzhdanNV** [comment]
>  This logic seems GAPI irrelevant, so better share it between D3D11/D3D12/VK.

Ooops. My bad. Not needed for D3D, because there is always full support for those.

**Comment by dzhdanNV** [comment]
Summary:
- please, explain your problem
  - list of surface formats you have
  - desired but unselected surface format 
- this code is not needed for D3D
- polish the PR and I will merge it

**Comment by pollend** [comment]
> Sure. This logic seems GAPI irrelevant, so better share it between D3D11/D3D12/VK.
> 
> Could you please formulate your problem? I understand that my simple checks "are not enough", but I didn't get which set of surface formats you have and which surface format from this list is not selected being desired?

```
// Color space:
//  - BT.709 - LDR https://en.wikipedia.org/wiki/Rec._709
//  - BT.2020 - HDR https://en.wikipedia.org/wiki/Rec._2020
// Transfer function:
//  - G10 - linear (gamma 1.0)
//  - G22 - sRGB (gamma ~2.2)
//  - G2084 - SMPTE ST.2084 (Perceptual Quantization)
// Bits per channel:
//  - 8, 10, 16 (float)
```

this is the criteria for the enum. My thought would be colorspace followed by format.  For the format I guess you would order by closest matching. would the order of the channels matter I wouldn't assume so since that is regardless of the shading code right? outputting to bgra is the same as rgba. Given the colorspace would shading logic change if a given colorspace is not available. ie my game is HDR but the swapchain doesn't support this. 

I haven't worked with other swap-chains so im not actually sure on the expectation. you can always add more bits if you want to prioritize one colorspace then the other if one is closer then the other color space.

**Comment by dzhdanNV** [comment]
> outputting to bgra is the same as rgba

Right. Unless you want to access the texture in a shader code. Not a big problem, since NRI returns swap chain format (in one way or another), so the app is aware.

Agree with the rest.

Do you plan to add more changes?

**Comment by pollend** [comment]
> > outputting to bgra is the same as rgba
> 
> Right. Unless you want to access the texture in a shader code. Not a big problem, since NRI returns swap chain format (in one way or another), so the app is aware.
> 
> Agree with the rest.
> 
> Do you plan to add more changes?

I'll quickly make the changes unless its easier on your end to just rework what i have.

**Comment by pollend** [comment]
> > outputting to bgra is the same as rgba
> 
> Right. Unless you want to access the texture in a shader code. Not a big problem, since NRI returns swap chain format (in one way or another), so the app is aware.
> 
> Agree with the rest.
> 
> Do you plan to add more changes?

the original code was a bit overbuilt i think these criteria should be a good start if it needs to be adjusted that can always happen later.

**Comment by dzhdanNV** [comment]
Thanks Michael. This is a solid starting point.

**Pull request merged**
