### PR TITLE
Added support for swapchain resize

### PR DESCRIPTION
**Pull request by vertver**

### CODE REVIEW

**Comment by dzhdanNV** [comment]
Thank you! Useful stuff. Integrating "as is" but `DXGI_SWAP_CHAIN_FLAG_FRAME_LATENCY_WAITABLE_OBJECT` requires changes around `SetMaximumFrameLatency`.

**Comment by vertver** [comment]
This also requires changes to the resize function itself (you need to store a separate event that is raised when the DXGI presentation completes).

**Comment by dzhdanNV** [comment]
I learned the API a bit:
- `DXGI_SWAP_CHAIN_FLAG_FRAME_LATENCY_WAITABLE_OBJECT` usage is recommended, but `pSwapChain2->GetFrameLatencyWaitableObject` must be used in conjunction with this flag
- I don't want to introduce a new function, like `WaitForFrame`... we already have `AcquireNextSwapChainTexture`! It looks like a perfect place!
- no changes in VK, because "acquiring" uses semaphores under the hood

Does it sound good? Gonna implement this for D3D11/D3D12 right now...

**Comment by vertver** [comment]
I think this is a good idea! And maybe also add a flag for the no wait function if possible.

**Comment by dzhdanNV** [comment]
Currently I'm against adding a flag for "not wait", because `DXGI_SWAP_CHAIN_FLAG_FRAME_LATENCY_WAITABLE_OBJECT` actually made behavior similar to VK, which is always waitable.

**Comment by dzhdanNV** [comment]
Implemented in v1.106. Just today noticed that `ResizeBuffers` was not added to the swap chain function table in `validation`. Fixed in my local version.

**Comment by dzhdanNV** [comment]
@vertver I'm about to remove `ResizeBuffers` because it's the same as:
```
// By spec
NRI.WaitForIdle(*m_CommandQueue);

// If created, destroy descriptors for old swapchain textures
NRI.DestroyDescriptor(*backBuffer.colorAttachment);

// Destroy old swapchain
NRI.DestroySwapChain(*m_SwapChain);

// Create new swapchain
nri::SwapChainDesc swapChainDesc = {...};
NRI.CreateSwapChain(*m_Device, swapChainDesc, m_SwapChain);

// Optionally create new descriptors for new swapchain textures
uint32_t swapChainTextureNum = 0;
nri::Texture* const* swapChainTextures = NRI.GetSwapChainTextures(*m_SwapChain, swapChainTextureNum);
...
```
My points:
- `Resize` implicitly changes internal textures, what leads to confusion and crashes
- `WaitForIdle` is needed in any case
- VK implementation uses `Destroy-Create`  under the hood

What do you think?

**Comment by vertver** [comment]
I implemented this functionality for D3D12 (and especially D3D11) because there were problems with resizing buffers in real time (ImGui docking branch as reference). When I did this via Destroy and Create, I was getting weird validation errors on D3D12 with texture layout (in very rare cases, but still). So I decided to create the resize functionality and after that it disappeared.

**Comment by dzhdanNV** [comment]
Your argumentation sounds like you wanted to find a workaround for a specific problem. It should not invoke API changes, IMO. Let's focus on fixing your problem - can you share the error reported by D3D debug layer, please? Plus, from the `ResizeBuffers` doc:
```
You can't resize a swap chain unless you release all outstanding references to its back buffers. You must
release all of its direct and indirect references on the back buffers in order for ResizeBuffers to succeed.
```
it implies `WaitForIdle`. In my case resizing to / from a specific resolution in one step works fine with the code I posted above. Dynamic resizing (with up to +/- 1 pixel step) is very unfriendly to modern APIs and must be avoided at all costs. As a workaround, you can create a swapchain, which is larger then window. It will allow you to freely resize the window without touching the swapchain.

**Comment by vertver** [comment]
> Let's focus on fixing your problem - can you share the error reported by D3D debug layer, please?

Can't do this right now, rewriting some rendering code to support BeginRendering/EndRendering :)

> it implies WaitForIdle

Fair point, but it doesn't solve my problem with application resizing. Mainly because GDK doesn't really like to recreate the swapchain when resizing (for example: when you change the quality settings from "Performance" to "Quality", it might also change the swapchain output resolution from FHD to QHD or UHD). "ResizeBuffers" is mainly designed for Windows platforms, so if we can find a solution for them - then we don't need additional functionality for resizing.

> As a workaround, you can create a swapchain, which is larger then window.

Not a deal for Vulkan applications (check an (VK_KHR_swapchain)[https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_swapchain.html] with VK_SUBOPTIMAL_KHR for more information). You can't create a surface with other size than a window working rect.

> Dynamic resizing (with up to +/- 1 pixel step) is very unfriendly to modern APIs and must be avoided at all costs. 

This does not apply to D3D11. D3D11 really don't like recreating swap chains on every resize event, so this change was made specifically for D3D11 and partly for D3D12.

**Comment by dzhdanNV** [comment]
> D3D11 really don't like recreating swap chains on every resize event

A-ha. So you try to dynamically adjust window and swapchain size. IMO, better "enter resize" => "resize without touching the swapchain" => "leave resize and update swapchain"

How do you handle swapchain descriptors (SRV, RTV), which become invalid after `ResizeBuffers`?

**Comment by vertver** [comment]
> "enter resize" => "resize without touching the swapchain" => "leave resize and update swapchain"

I used to do that, but ImGui with docking mode doesn't like it very much. On D3D12 it seems to work (but not perfectly, just blinks a lot), but on D3D11 it *randomly* crashes with an error that says I haven't released all the swapchain resources, which is not true.

> How do you handle swapchain descriptors (SRV, RTV)

```cpp
  WaitForIdle();

    Viewport* CurrentViewport = GetViewport(NativeWindow);
    if (CurrentViewport == nullptr) {
        Debug::Failure(Debug::Category_Render, "Failed to resize viewport, because it doesn't exist.");
        return false;
    }

    // When resizing, the frame fence must be reset to 0 because the frame counter has also been reset  
    if (CurrentViewport->FrameFence != nullptr) {
        RHI::Core::DestroyFence(*CurrentViewport->FrameFence);
        CurrentViewport->FrameFence = nullptr;
    }

    int Width = 0;
    int Height = 0;
    SDL_GetWindowSizeInPixels(CurrentViewport->Window, &Width, &Height);

    if (CurrentViewport->SwapChainHandle != nullptr) {
        RHI::Result Result = RHI::Swapchain::ResizeBuffers(*CurrentViewport->SwapChainHandle, Width, Height);
        if (Result != RHI::Result::SUCCESS) {
            Debug::Failure(Debug::Category_Render, "hey");
            return false;
        }

        std::uint32_t SwapChainTextureNum = 0;
        RHI::Texture* const* SwapChainTextures = RHI::Swapchain::GetSwapChainTextures(*CurrentViewport->SwapChainHandle, SwapChainTextureNum, SwapChainFormat);
        EngineFrameCount = static_cast<std::int32_t>(SwapChainTextureNum);
        std::memcpy(CurrentViewport->SwapChainTextures.data(), SwapChainTextures, sizeof(RHI::SwapChain*) * SwapChainTextureNum);

        CurrentViewport->Width = Width;
        CurrentViewport->Height = Height;
    }
```

**Comment by dzhdanNV** [comment]
I managed to get "resize" working via "Destroy-Create" for all APIs. Most problematic one was D3D11. The debug layer said:
```
DXGI ERROR: IDXGIFactory::CreateSwapChain: Only one flip model swap chain can be associate with an HWND,
IWindow, or composition surface at a time. ClearState() and Flush() may need to be called on the D3D11 device
context to trigger deferred destruction of old swapchains. [ MISCELLANEOUS ERROR #297: ]
```
After hours of debugging I realized that this error happened only if D3D11 deferred contexts were active. The fix is simple (resources were implicitly referenced inside a `ID3D11CommandList`):
```
void CommandBufferD3D11::Submit()
{
    m_Device.GetImmediateContext()->ExecuteCommandList(m_CommandList, FALSE);
    m_CommandList = nullptr; <====== add this line
}
```
In one of last comments you mentioned that D3D12 worked, but D3D11 did not. Please, try this fix on your end. I would really like to drop `ResizeBuffers` which is needed only for D3D11, which in order is not the 1st class citizen definitely.

BTW, there is a minor issue in D3D11/D3D12 swapchains - background color has 0 alpha, it doesn't look good. Fix is simple:
```
DXGI_RGBA color = {}; <===== find this
DXGI_RGBA color = {0.0f, 0.0f, 0.0f, 1.0f} <===== replace with this
```
Waiting for your feedback...

**Comment by vertver** [comment]
> Waiting for your feedback...

Yes, this may work correctly, if this case works for D3D11 - then it can be removed.

**Pull request merged**
