### PR TITLE
Use optimal layout for texture copying

### PR DESCRIPTION
**Pull request by vertver**

### CODE REVIEW

**Comment by dzhdanNV** [comment]
Thank you! I don't recall the exact reason why COPY states were not exposed at the beginning. AFAIR, the reason was simple - usage complexity. Old VK validation was silent.

**Comment by dzhdanNV** [comment]
@vertver There were other places using `vkCmdCopy...` which used `GENERAL`. I fixed it. Fix will be included into the next update.

**Comment by vertver** [comment]
Thanks. I'll check them

**Comment by dzhdanNV** [comment]
I'm removing newly added `COPY_SOURCE` and `COPY_DESTINATION` texture layouts. There is no a benefit in using `VK_IMAGE_LAYOUT_TRANSFER_*_OPTIMAL` instead of `VK_IMAGE_LAYOUT_GENERAL` on NV HW at least. But the complexity of usage increases, potentially adding more transition barriers. Additional point - these do not exist in D3D12, what already implies that usefulness of those on desktop is minimal on any desktop HW.

**Comment by dzhdanNV** [comment]
But your change is useful, in VK implementation I added this:
```
// TODO: no benefit on desktop from "IMAGE_LAYOUT_TRANSFER_*_OPTIMAL" but keep for future needs
#if 0
    #define IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL
    #define IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL
#else
    #define IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL VK_IMAGE_LAYOUT_GENERAL
    #define IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL VK_IMAGE_LAYOUT_GENERAL
#endif
```
VK spec does allow to use `GENERAL`. There is a validation message (not error) suggesting using `TRANSFER` instead, but it was silenced in NRI ages ago.

TL/DR: `TRANSFER` adds complexity in usage without giving a performance benefit.

**Comment by vertver** [comment]
> There is no a benefit in using VK_IMAGE_LAYOUT_TRANSFER_*_OPTIMAL instead of VK_IMAGE_LAYOUT_GENERAL on NV HW at least.

But on AMD, it [makes a difference](https://github.com/Mesa3D/mesa/blob/957009978ef6d7121fc0d710d03bc20097d4d46b/src/amd/vulkan/radv_image.c#L2463).

> Additional point - these do not exist in D3D12

They [does](https://microsoft.github.io/DirectX-Specs/d3d/D3D12EnhancedBarriers.html#d3d12_barrier_layout). But it is fair to say that it is not supported on older drivers.

**Comment by dzhdanNV** [comment]
OK. You convinced me - `COPY_SOURCE` and `COPY_DESTINATION` stay. Probably, AMD is one of reasons why enhanced barriers appeared.

**Pull request merged**
